"""
BuyLabel enum — binary recommendation label generated by the ML model.
Use this enum everywhere instead of raw strings or booleans.
"""
from enum import Enum


class BuyLabel(str, Enum):
    BUY     = "Buy"
    NOT_BUY = "Not Buy"

    @classmethod
    def from_int(cls, value: int) -> "BuyLabel":
        """Convert model output (1 = buy, 0 = not buy) to BuyLabel."""
        return cls.BUY if value == 1 else cls.NOT_BUY

    @classmethod
    def from_bool(cls, value: bool) -> "BuyLabel":
        return cls.BUY if value else cls.NOT_BUY
